services:
  backend-postgres:
    image: postgres:18.3
    environment:
      POSTGRES_USER: ${BACKEND_POSTGRES_USER}
      POSTGRES_PASSWORD: ${BACKEND_POSTGRES_PASSWORD}
      POSTGRES_DB: ${BACKEND_POSTGRES_DB}
      POSTGRES_CONSUMER_USER: ${BACKEND_POSTGRES_CONSUMER_USER}
      POSTGRES_CONSUMER_PASSWORD: ${BACKEND_POSTGRES_CONSUMER_PASSWORD}
      POSTGRES_ETL_USER: ${BACKEND_POSTGRES_ETL_USER}
      POSTGRES_ETL_PASSWORD: ${BACKEND_POSTGRES_ETL_PASSWORD}
      LOGGER_USER: ${LOGGER_USER}
      LOGGER_PASSWORD: ${LOGGER_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
    networks:
      - backend_store_network
      - etl_store_network
    ports:
      - "127.0.0.1:${LOCAL_BACKEND_POSTGRES_PORT}:${BACKEND_POSTGRES_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${BACKEND_POSTGRES_USER} -d ${BACKEND_POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    environment:
      POSTGRES_USER: ${BACKEND_POSTGRES_USER}
      POSTGRES_PASSWORD: ${BACKEND_POSTGRES_PASSWORD}
      POSTGRES_DB: ${BACKEND_POSTGRES_DB}
      POSTGRES_PORT: ${BACKEND_POSTGRES_PORT}
      POSTGRES_CONSUMER_USER: ${BACKEND_POSTGRES_CONSUMER_USER}
      POSTGRES_CONSUMER_PASSWORD: ${BACKEND_POSTGRES_CONSUMER_PASSWORD}
      BACKEND_PORT: ${BACKEND_PORT}
      CLICKHOUSE_HTTP_PORT: ${LOG_CLICKHOUSE_HTTP_PORT}
      CLICKHOUSE_DB: ${LOG_CLICKHOUSE_DB}
      LOGGER_USER: ${LOGGER_USER}
      LOGGER_PASSWORD: ${LOGGER_PASSWORD}
    ports:
      - "127.0.0.1:${LOCAL_BACKEND_PORT}:${BACKEND_PORT}"
    networks:
      - etl_store_network
      - backend_store_network
    depends_on:
      backend-postgres:
        condition: service_healthy
      log-clickhouse:
        condition: service_healthy

  log-clickhouse:
    image: clickhouse/clickhouse-server:25.1.2.3
    environment:
      CLICKHOUSE_USER: ${LOG_CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${LOG_CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DB: ${LOG_CLICKHOUSE_DB}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: ${LOG_CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT}
      LOGGER_USER: ${LOGGER_USER}
      LOGGER_PASSWORD: ${LOGGER_PASSWORD}
    ports:
      - "127.0.0.1:${LOCAL_CLICKHOUSE_LOG_HTTP_PORT}:${LOG_CLICKHOUSE_HTTP_PORT}"
      - "127.0.0.1:${LOCAL_CLICKHOUSE_LOG_APPLICATION_PORT}:${LOG_CLICKHOUSE_APPLICATION_PORT}"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./init/init_clickhouse.sh:/docker-entrypoint-initdb.d/init-clickhouse.sh
    networks:
      - etl_store_network
      - backend_store_network
    healthcheck:
      test: ["CMD", "clickhouse", "client", "-q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  postgres_data:
  clickhouse_data:

networks:
  etl_store_network:
    external: true
    name: etl_store_network
  backend_store_network:
    name: backend_store_network