services:
  dwh-postgres:
    build: ./postgres
    container_name: dwh-postgres
    command: >
      postgres
      -c shared_preload_libraries=pg_cron
      -c cron.database_name=${DWH_POSTGRES_DB}
    environment:
      POSTGRES_USER: ${DWH_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DWH_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DWH_POSTGRES_DB}
      DWH_LOAD_STAGING_USER: ${DWH_LOAD_STAGING_USER}
      DWH_LOAD_STAGING_PASSWORD: ${DWH_LOAD_STAGING_PASSWORD}
      DWH_STAGING_TO_RAW_VAULT_USER: ${DWH_STAGING_TO_RAW_VAULT_USER}
      DWH_STAGING_TO_RAW_VAULT_PASSWORD: ${DWH_STAGING_TO_RAW_VAULT_PASSWORD}
      DWH_PG_RAW_VAULT_TO_DATA_MART_USER: ${DWH_PG_RAW_VAULT_TO_DATA_MART_USER}
      DWH_PG_RAW_VAULT_TO_DATA_MART_PASSWORD: ${DWH_PG_RAW_VAULT_TO_DATA_MART_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - etl_store_network
    ports:
      - "127.0.0.1:${LOCAL_DWH_POSTGRES_PORT}:${DWH_POSTGRES_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DWH_POSTGRES_USER} -d ${DWH_POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  dwh-clickhouse:
    image: clickhouse/clickhouse-server:25.1.2.3
    container_name: dwh-clickhouse
    environment:
      CLICKHOUSE_USER: ${DWH_CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${DWH_CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DB: ${DWH_CLICKHOUSE_DB}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: ${DWH_CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT}
      DWH_CH_RAW_VAULT_TO_DATA_MART_USER: ${DWH_CH_RAW_VAULT_TO_DATA_MART_USER}
      DWH_CH_RAW_VAULT_TO_DATA_MART_PASSWORD: ${DWH_CH_RAW_VAULT_TO_DATA_MART_PASSWORD}
      DWH_DATA_MART_TO_INFO_MART_USER: ${DWH_DATA_MART_TO_INFO_MART_USER}
      DWH_DATA_MART_TO_INFO_MART_PASSWORD: ${DWH_DATA_MART_TO_INFO_MART_PASSWORD}
      DWH_INFO_MART_TO_SUPERSET_USER: ${DWH_INFO_MART_TO_SUPERSET_USER}
      DWH_INFO_MART_TO_SUPERSET_PASSWORD: ${DWH_INFO_MART_TO_SUPERSET_PASSWORD}
    ports:
      - "127.0.0.1:${LOCAL_CLICKHOUSE_DWH_HTTP_PORT}:${DWH_CLICKHOUSE_HTTP_PORT}"
      - "127.0.0.1:${LOCAL_CLICKHOUSE_DWH_APPLICATION_PORT}:${DWH_CLICKHOUSE_APPLICATION_PORT}"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse/01_init_db.sql:/docker-entrypoint-initdb.d/01_init_db.sql
      - ./clickhouse/02_init_db.sh:/docker-entrypoint-initdb.d/02_init_db.sh
    networks:
      - etl_store_network
      - info_mart_network
    healthcheck:
      test: ["CMD", "clickhouse", "client", "-q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  postgres_data:
  clickhouse_data:

networks:
  etl_store_network:
    external: true
    name: etl_store_network
  info_mart_network:
    external: true
    name: info_mart_network